name: Simple Go Build
on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go version
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - run: go run hello.go Bonjour le monde
